# Generated by Django 4.2 on 2023-04-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_outbound'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.product')),
                ('total_inbound', models.IntegerField(default=0)),
                ('total_outbound', models.IntegerField(default=0)),
                ('total_inbound_price', models.IntegerField(default=0)),
                ('total_outbound_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='inbound_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
