# Generated by Django 4.2 on 2023-04-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_inventory_product_inbound_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
