# Generated by Django 4.2 on 2023-04-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
