# Generated by Django 4.2 on 2023-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
